"""
shorts_renderer.py — Renders a YouTube Short (9:16 vertical) using:
  - Gradient background generated by Pillow (no B-roll footage needed)
  - Animated text overlays burned in via FFmpeg overlay filter
  - Voiceover audio from ElevenLabs

Output: workspace/output/short_original.mp4
"""
import json
import logging
import subprocess
from pathlib import Path
from typing import Optional

from pipeline.renderer import _bin

logger = logging.getLogger(__name__)

WORKSPACE = Path("workspace")
OUTPUT_SHORT = WORKSPACE / "output" / "short_original.mp4"
BGMUSIC_PATH = Path("pipeline/assets/bgmusic.mp3")

# YouTube Shorts dimensions
SHORT_W = 1080
SHORT_H = 1920

WPS = 2.5  # words per second

# Brand color palette — dark background, high contrast text
BACKGROUNDS = [
    [(15, 15, 25), (30, 30, 60)],      # deep navy
    [(10, 20, 10), (20, 50, 30)],      # dark green (investing)
    [(25, 10, 10), (60, 20, 20)],      # dark red (debt urgency)
    [(15, 10, 25), (40, 20, 60)],      # deep purple
    [(10, 20, 30), (20, 50, 80)],      # ocean blue
]


def _get_font(size: int):
    from PIL import ImageFont
    candidates = [
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/Arial Unicode.ttf",
        "/Library/Fonts/Arial Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except (IOError, OSError):
            continue
    return ImageFont.load_default(size=size)


def _make_gradient_background(color_top: tuple, color_bottom: tuple,
                               w: int = SHORT_W, h: int = SHORT_H):
    """Generate a vertical gradient background image."""
    from PIL import Image
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    for y in range(h):
        t = y / h
        r = int(color_top[0] + (color_bottom[0] - color_top[0]) * t)
        g = int(color_top[1] + (color_bottom[1] - color_top[1]) * t)
        b = int(color_top[2] + (color_bottom[2] - color_top[2]) * t)
        for x in range(w):
            pixels[x, y] = (r, g, b)
    return img


def _draw_centered(draw, text: str, y: int, font, fill, width: int, shadow: bool = True):
    from PIL import ImageDraw  # noqa
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    x = (width - tw) // 2
    if shadow:
        draw.text((x + 3, y + 3), text, font=font, fill=(0, 0, 0, 180))
    draw.text((x, y), text, font=font, fill=fill)


def _make_overlay_image(overlay: dict, w: int = SHORT_W, h: int = SHORT_H):
    """Render one overlay dict to a transparent RGBA PIL Image."""
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    otype = overlay.get("type")

    if otype == "hook_number":
        # Giant number — center of screen, yellow, massive font
        text = overlay.get("text", "")
        font_big = _get_font(160)
        font_sub = _get_font(52)
        # Dark pill background
        bbox = draw.textbbox((0, 0), text, font=font_big)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        pad = 40
        x0 = (w - tw) // 2 - pad
        y0 = int(h * 0.30)
        draw.rounded_rectangle(
            [(x0, y0 - pad // 2), (x0 + tw + pad * 2, y0 + th + pad)],
            radius=24, fill=(0, 0, 0, 200)
        )
        _draw_centered(draw, text, y0, font_big, (255, 220, 50, 255), w)
        # Subtitle below
        subtitle = overlay.get("subtitle", "")
        if subtitle:
            _draw_centered(draw, subtitle, y0 + th + pad + 10, font_sub, (200, 200, 200, 230), w)

    elif otype == "label":
        text = overlay.get("text", "").upper()
        font = _get_font(64)
        bbox = draw.textbbox((0, 0), text, font=font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        pad = 20
        x0 = (w - tw) // 2 - pad
        y0 = int(h * 0.72)
        draw.rounded_rectangle(
            [(x0, y0 - pad // 2), (x0 + tw + pad * 2, y0 + th + pad)],
            radius=16, fill=(255, 255, 255, 25)
        )
        _draw_centered(draw, text, y0, font, (255, 255, 255, 255), w, shadow=True)

    elif otype == "comparison":
        # Split left/right comparison card
        left = overlay.get("left", "")
        right = overlay.get("right", "")
        draw.rectangle([(0, int(h * 0.35)), (w, int(h * 0.65))], fill=(0, 0, 0, 180))
        draw.line([(w // 2, int(h * 0.37)), (w // 2, int(h * 0.63))],
                  fill=(100, 100, 100, 200), width=3)
        hfont = _get_font(44)
        vfont = _get_font(52)
        # Headers
        draw.text((int(w * 0.08), int(h * 0.37)), "BEFORE", font=hfont, fill=(255, 80, 80, 255))
        draw.text((int(w * 0.58), int(h * 0.37)), "AFTER", font=hfont, fill=(80, 220, 100, 255))
        # Values
        for i, line in enumerate(left.split("\n")[:3]):
            draw.text((int(w * 0.06), int(h * (0.44 + i * 0.07))), line,
                      font=vfont, fill=(255, 255, 255, 255))
        for i, line in enumerate(right.split("\n")[:3]):
            draw.text((int(w * 0.56), int(h * (0.44 + i * 0.07))), line,
                      font=vfont, fill=(255, 255, 255, 255))

    elif otype == "cta":
        text = overlay.get("text", "Follow for more")
        font = _get_font(58)
        bbox = draw.textbbox((0, 0), text, font=font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        pad = 28
        x0 = (w - tw) // 2 - pad
        y0 = int(h * 0.80)
        draw.rounded_rectangle(
            [(x0, y0 - pad // 2), (x0 + tw + pad * 2, y0 + th + pad)],
            radius=20, fill=(255, 220, 50, 230)
        )
        _draw_centered(draw, text, y0, font, (0, 0, 0, 255), w, shadow=False)

    return img


def _render_overlay_frames(overlays: list, work_dir: Path) -> list:
    """Generate transparent PNGs for each overlay. Returns overlays with frame_path added."""
    try:
        from PIL import Image  # noqa
    except ImportError:
        logger.warning("Pillow not installed — skipping overlays")
        return []

    overlay_dir = work_dir / "short_overlays"
    overlay_dir.mkdir(parents=True, exist_ok=True)

    result = []
    for i, ov in enumerate(overlays):
        img = _make_overlay_image(ov)
        path = overlay_dir / f"overlay_{i:02d}.png"
        img.save(path)
        result.append({**ov, "frame_path": str(path)})
        logger.debug("Rendered Short overlay %d: type=%s", i, ov.get("type"))

    logger.info("Rendered %d Short overlay frames", len(result))
    return result


def _generate_background_video(work_dir: Path, duration: float,
                                pillar: str = "investing") -> Path:
    """
    Generate a gradient background video using Pillow + FFmpeg.
    Creates a static gradient image, then uses FFmpeg to loop it for the duration.
    """
    from PIL import Image

    # Pick color scheme by pillar
    palette_map = {
        "investing": BACKGROUNDS[0],
        "budgeting": BACKGROUNDS[4],
        "debt": BACKGROUNDS[2],
        "tax": BACKGROUNDS[3],
        "career_income": BACKGROUNDS[1],
    }
    colors = palette_map.get(pillar, BACKGROUNDS[0])
    bg_img = _make_gradient_background(colors[0], colors[1])

    # Add subtle ClearWealth watermark
    from PIL import ImageDraw
    draw = ImageDraw.Draw(bg_img)
    font = _get_font(36)
    draw.text((SHORT_W // 2 - 80, int(SHORT_H * 0.05)), "ClearWealth",
              font=font, fill=(255, 255, 255, 60))

    bg_path = work_dir / "bg_frame.png"
    bg_img.save(bg_path)

    bg_video = work_dir / "bg_video.mp4"
    cmd = [
        _bin("ffmpeg"), "-y",
        "-loop", "1",
        "-i", str(bg_path),
        "-t", str(duration + 2),
        "-vf", f"scale={SHORT_W}:{SHORT_H},fps=30",
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28",
        "-pix_fmt", "yuv420p",
        str(bg_video),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        raise RuntimeError(f"Background video generation failed:\n{result.stderr[-500:]}")

    logger.info("Background video generated: %.1fs", duration)
    return bg_video


def _get_voiceover_duration(path: Path) -> float:
    result = subprocess.run(
        [_bin("ffprobe"), "-v", "quiet", "-print_format", "json", "-show_format", str(path)],
        capture_output=True, text=True, timeout=30, check=True,
    )
    return float(json.loads(result.stdout)["format"]["duration"])


def render(
    voiceover_path: Path,
    script_data: dict,
    output_path: Path = OUTPUT_SHORT,
    bgmusic_path: Path = BGMUSIC_PATH,
) -> Path:
    """
    Render a standalone YouTube Short.
    - Generates gradient background
    - Burns in text overlays
    - Mixes voiceover + soft background music
    Returns path to output file.
    """
    if not voiceover_path.exists():
        raise FileNotFoundError(f"Voiceover not found: {voiceover_path}")

    work_dir = WORKSPACE / "short_work"
    work_dir.mkdir(parents=True, exist_ok=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    vo_duration = _get_voiceover_duration(voiceover_path)
    logger.info("Short voiceover duration: %.1fs", vo_duration)

    pillar = script_data.get("pillar", "investing")
    bg_video = _generate_background_video(work_dir, vo_duration, pillar)

    overlays = script_data.get("overlays", [])
    rendered_overlays = _render_overlay_frames(overlays, work_dir)

    if rendered_overlays:
        # Build overlay filter chain
        n = len(rendered_overlays)
        extra_inputs = []
        for ov in rendered_overlays:
            extra_inputs.extend(["-loop", "1", "-i", str(ov["frame_path"])])

        chains = []
        prev = "0:v"
        for i, ov in enumerate(rendered_overlays):
            out = f"vout{i}" if i < n - 1 else "vout"
            start = round(int(ov.get("start_word", 0)) / WPS, 2)
            end = round(start + float(ov.get("duration_s", 3.0)), 2)
            chains.append(
                f"[{prev}][{i + 1}:v]overlay=0:0:enable='between(t,{start},{end})'[{out}]"
            )
            prev = out

        vo_idx = n + 1
        bg_idx = n + 2

        if bgmusic_path.exists():
            audio_filter = (
                f"[{vo_idx}:a]volume=1.0[voice];"
                f"[{bg_idx}:a]volume=0.08[music];"
                "[voice][music]amix=inputs=2:duration=first[a]"
            )
            audio_inputs = ["-i", str(voiceover_path), "-i", str(bgmusic_path)]
        else:
            audio_filter = f"[{vo_idx}:a]volume=1.0[a]"
            audio_inputs = ["-i", str(voiceover_path)]
            vo_idx = n + 1

        filter_complex = ";".join(chains) + ";" + audio_filter

        cmd = [
            _bin("ffmpeg"), "-y",
            "-i", str(bg_video),
            *extra_inputs,
            *audio_inputs,
            "-filter_complex", filter_complex,
            "-map", "[vout]",
            "-map", "[a]",
            "-c:v", "libx264", "-preset", "fast", "-crf", "20",
            "-c:a", "aac", "-b:a", "128k",
            "-r", "30",
            "-movflags", "+faststart",
            "-shortest",
            str(output_path),
        ]
    else:
        # No overlays — just mix audio over background
        if bgmusic_path.exists():
            filter_complex = (
                "[1:a]volume=1.0[voice];[2:a]volume=0.08[music];"
                "[voice][music]amix=inputs=2:duration=first[a]"
            )
            cmd = [
                _bin("ffmpeg"), "-y",
                "-i", str(bg_video),
                "-i", str(voiceover_path),
                "-i", str(bgmusic_path),
                "-filter_complex", filter_complex,
                "-map", "0:v",
                "-map", "[a]",
                "-c:v", "copy",
                "-c:a", "aac", "-b:a", "128k",
                "-movflags", "+faststart",
                "-shortest",
                str(output_path),
            ]
        else:
            cmd = [
                _bin("ffmpeg"), "-y",
                "-i", str(bg_video),
                "-i", str(voiceover_path),
                "-map", "0:v", "-map", "1:a",
                "-c:v", "copy",
                "-c:a", "aac", "-b:a", "128k",
                "-movflags", "+faststart",
                "-shortest",
                str(output_path),
            ]

    logger.info("Rendering Short: %d overlays", len(rendered_overlays))
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        raise RuntimeError(f"Short render failed:\n{result.stderr[-1000:]}")

    if not output_path.exists() or output_path.stat().st_size < 50_000:
        raise RuntimeError(f"Short output missing or too small: {output_path}")

    logger.info("Short rendered: %s (%.1f MB)", output_path,
                output_path.stat().st_size / 1_048_576)
    return output_path
