"""
shorts_renderer.py — Renders a YouTube Short (9:16 vertical) using:
  - Gradient background generated by Pillow (no B-roll footage needed)
  - Overlays pre-baked into background frames via Pillow compositing (no FFmpeg filter graph)
  - Cadence labels injected to fill any visual gap > MAX_VISUAL_GAP_S
  - Loudness-normalized audio mix

Output: workspace/output/short_original.mp4
"""
import json
import logging
import math
import re
import subprocess
from pathlib import Path

from pipeline.renderer import _bin

logger = logging.getLogger(__name__)

WORKSPACE = Path("workspace")
OUTPUT_SHORT = WORKSPACE / "output" / "short_original.mp4"
BGMUSIC_PATH = Path("pipeline/assets/bgmusic.mp3")

SHORT_W = 1080
SHORT_H = 1920

WPS = 2.5               # words per second at voiceover pace
MAX_VISUAL_GAP_S = 2.0  # max seconds of blank screen before injecting a cadence label
MAX_LINE_CHARS = 20     # fallback char-wrap width (word-boundary fallback only)
TARGET_LOUDNESS = -16.0

BACKGROUNDS = [
    [(15, 15, 25), (30, 30, 60)],    # deep navy  (investing)
    [(10, 20, 10), (20, 50, 30)],    # dark green (career_income)
    [(25, 10, 10), (60, 20, 20)],    # dark red   (debt)
    [(15, 10, 25), (40, 20, 60)],    # deep purple(tax)
    [(10, 20, 30), (20, 50, 80)],    # ocean blue (budgeting)
]


# ---------------------------------------------------------------------------
# Font helpers
# ---------------------------------------------------------------------------

def _get_font(size: int):
    from PIL import ImageFont
    candidates = [
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/Arial Unicode.ttf",
        "/Library/Fonts/Arial Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except (IOError, OSError):
            continue
    return ImageFont.load_default(size=size)


def _clean_text(value: str) -> str:
    return " ".join(str(value or "").split()).strip()


def _text_width(draw, text: str, font) -> int:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0]


def _text_height(draw, text: str, font) -> int:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[3] - bbox[1]


def _truncate_to_width(draw, text: str, font, max_width: int) -> str:
    if not text:
        return ""
    out = text
    while out and _text_width(draw, out, font) > max_width:
        if len(out) <= 1:
            break
        out = out[:-1]
    return out.rstrip() + ("..." if out != text else "")


def _wrap_fit_lines(
    draw,
    text: str,
    max_width: int,
    start_size: int,
    min_size: int,
    max_lines: int = 2,
):
    """
    Try progressively smaller font sizes until the text fits within max_lines.
    Hard fallback: split on word boundaries (not character boundaries) and truncate.
    """
    words = _clean_text(text).split()
    if not words:
        return [""], _get_font(min_size)

    for size in range(start_size, min_size - 1, -2):
        font = _get_font(size)
        lines: list[str] = []
        current = words[0]
        for word in words[1:]:
            candidate = f"{current} {word}"
            if _text_width(draw, candidate, font) <= max_width:
                current = candidate
            else:
                lines.append(current)
                current = word
        lines.append(current)

        if len(lines) <= max_lines and all(
            _text_width(draw, line, font) <= max_width for line in lines
        ):
            return lines, font

    # Hard fallback — split on word boundaries, not characters
    font = _get_font(min_size)
    words_per_line = math.ceil(len(words) / max_lines)
    lines = [
        " ".join(words[i: i + words_per_line])
        for i in range(0, len(words), words_per_line)
    ][:max_lines]
    lines = [_truncate_to_width(draw, line, font, max_width) for line in lines]
    return lines, font


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------

def _draw_centered(draw, text: str, y: int, font, fill, width: int, shadow: bool = True):
    tw = _text_width(draw, text, font)
    x = (width - tw) // 2
    if shadow:
        draw.text((x + 3, y + 3), text, font=font, fill=(0, 0, 0, 180))
    draw.text((x, y), text, font=font, fill=fill)


def _draw_multiline_centered(
    draw, lines: list[str], y: int, font, fill, width: int, gap: int = 8, shadow: bool = True
) -> int:
    """Draw centred multi-line text. Returns the y position after the last line."""
    current_y = y
    for line in lines:
        _draw_centered(draw, line, current_y, font, fill, width, shadow=shadow)
        current_y += _text_height(draw, line, font) + gap
    return current_y


# ---------------------------------------------------------------------------
# Background
# ---------------------------------------------------------------------------

def _make_gradient_background(color_top: tuple, color_bottom: tuple,
                               w: int = SHORT_W, h: int = SHORT_H):
    from PIL import Image
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    for y in range(h):
        t = y / h
        r = int(color_top[0] + (color_bottom[0] - color_top[0]) * t)
        g = int(color_top[1] + (color_bottom[1] - color_top[1]) * t)
        b = int(color_top[2] + (color_bottom[2] - color_top[2]) * t)
        for x in range(w):
            pixels[x, y] = (r, g, b)
    return img


def _make_background_image(pillar: str = "investing"):
    """Gradient background with watermark. Returns RGBA PIL Image."""
    from PIL import ImageDraw
    palette_map = {
        "investing":    BACKGROUNDS[0],
        "career_income": BACKGROUNDS[1],
        "debt":         BACKGROUNDS[2],
        "tax":          BACKGROUNDS[3],
        "budgeting":    BACKGROUNDS[4],
    }
    colors = palette_map.get(pillar, BACKGROUNDS[0])
    bg = _make_gradient_background(colors[0], colors[1]).convert("RGBA")
    draw = ImageDraw.Draw(bg)
    font = _get_font(36)
    draw.text(
        (SHORT_W // 2 - 80, int(SHORT_H * 0.05)),
        "ClearWealth",
        font=font,
        fill=(255, 255, 255, 60),
    )
    return bg


# ---------------------------------------------------------------------------
# Overlay card renderers
# ---------------------------------------------------------------------------

def _make_overlay_image(overlay: dict, w: int = SHORT_W, h: int = SHORT_H):
    """Render one overlay dict to a transparent RGBA PIL Image."""
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    otype = overlay.get("type")

    if otype == "hook_number":
        text = _clean_text(overlay.get("text", ""))
        subtitle = _clean_text(overlay.get("subtitle", ""))

        text_lines, text_font = _wrap_fit_lines(
            draw, text, max_width=int(w * 0.86), start_size=170, min_size=72, max_lines=2
        )
        text_block_h = sum(_text_height(draw, ln, text_font) for ln in text_lines) + \
                       8 * max(0, len(text_lines) - 1)

        subtitle_lines, subtitle_font, subtitle_block_h = [], None, 0
        if subtitle:
            subtitle_lines, subtitle_font = _wrap_fit_lines(
                draw, subtitle, max_width=int(w * 0.84), start_size=60, min_size=34, max_lines=2
            )
            subtitle_block_h = sum(_text_height(draw, ln, subtitle_font) for ln in subtitle_lines) + \
                                6 * max(0, len(subtitle_lines) - 1)

        pad_y = 22
        card_w = int(w * 0.90)
        card_h = text_block_h + subtitle_block_h + pad_y * 2 + (12 if subtitle_lines else 0)
        x0 = (w - card_w) // 2
        y0 = int(h * 0.26)
        draw.rounded_rectangle([(x0, y0), (x0 + card_w, y0 + card_h)], radius=28, fill=(0, 0, 0, 205))
        current_y = y0 + pad_y
        current_y = _draw_multiline_centered(draw, text_lines, current_y, text_font, (255, 220, 50, 255), w, gap=8)
        if subtitle_lines and subtitle_font is not None:
            current_y += 4
            _draw_multiline_centered(draw, subtitle_lines, current_y, subtitle_font, (215, 215, 215, 235), w, gap=6)

    elif otype == "label":
        text = _clean_text(overlay.get("text", "")).upper()
        lines, font = _wrap_fit_lines(draw, text, max_width=int(w * 0.78), start_size=66, min_size=34, max_lines=2)
        block_h = sum(_text_height(draw, ln, font) for ln in lines) + 8 * max(0, len(lines) - 1)
        pad = 18
        y0 = int(h * 0.72)
        card_w = int(w * 0.82)
        x0 = (w - card_w) // 2
        draw.rounded_rectangle(
            [(x0, y0), (x0 + card_w, y0 + block_h + pad * 2)], radius=16, fill=(255, 255, 255, 28)
        )
        _draw_multiline_centered(draw, lines, y0 + pad, font, (255, 255, 255, 255), w, gap=8)

    elif otype == "comparison":
        left = _clean_text(overlay.get("left", ""))
        right = _clean_text(overlay.get("right", ""))
        draw.rectangle([(0, int(h * 0.35)), (w, int(h * 0.65))], fill=(0, 0, 0, 180))
        draw.line([(w // 2, int(h * 0.37)), (w // 2, int(h * 0.63))], fill=(100, 100, 100, 200), width=3)
        hfont = _get_font(44)
        draw.text((int(w * 0.08), int(h * 0.37)), "BEFORE", font=hfont, fill=(255, 80, 80, 255))
        draw.text((int(w * 0.58), int(h * 0.37)), "AFTER",  font=hfont, fill=(80, 220, 100, 255))
        left_lines,  left_font  = _wrap_fit_lines(draw, left.replace("\n", " "),  int(w * 0.40), 52, 30, max_lines=3)
        right_lines, right_font = _wrap_fit_lines(draw, right.replace("\n", " "), int(w * 0.40), 52, 30, max_lines=3)
        for i, line in enumerate(left_lines[:3]):
            draw.text((int(w * 0.06), int(h * (0.44 + i * 0.07))), line, font=left_font,  fill=(255, 255, 255, 255))
        for i, line in enumerate(right_lines[:3]):
            draw.text((int(w * 0.56), int(h * (0.44 + i * 0.07))), line, font=right_font, fill=(255, 255, 255, 255))

    elif otype == "cta":
        text = _clean_text(overlay.get("text", "Follow for more"))
        lines, font = _wrap_fit_lines(draw, text, max_width=int(w * 0.80), start_size=58, min_size=32, max_lines=2)
        block_h = sum(_text_height(draw, ln, font) for ln in lines) + 8 * max(0, len(lines) - 1)
        pad = 24
        y0 = int(h * 0.80)
        card_w = int(w * 0.84)
        x0 = (w - card_w) // 2
        draw.rounded_rectangle(
            [(x0, y0), (x0 + card_w, y0 + block_h + pad * 2)], radius=20, fill=(255, 220, 50, 230)
        )
        _draw_multiline_centered(draw, lines, y0 + pad, font, (0, 0, 0, 255), w, gap=8, shadow=False)

    return img


# ---------------------------------------------------------------------------
# Overlay helpers
# ---------------------------------------------------------------------------

def _ov_start(ov: dict) -> float:
    return round(int(ov.get("start_word", 0)) / WPS, 2)


def _ov_end(ov: dict) -> float:
    return round(_ov_start(ov) + float(ov.get("duration_s", 3.0)), 2)


def _sanitize_overlays(overlays: list, duration_s: float) -> list[dict]:
    safe = []
    for ov in overlays:
        kind = str((ov or {}).get("type", "")).strip()
        if kind not in {"hook_number", "label", "comparison", "cta"}:
            continue
        try:
            start_word = max(0, int((ov or {}).get("start_word", 0)))
        except (TypeError, ValueError):
            start_word = 0
        try:
            dur = max(1.2, min(float((ov or {}).get("duration_s", 3.0)), 5.0))
        except (TypeError, ValueError):
            dur = 3.0
        if start_word / WPS >= duration_s:
            continue
        cleaned = dict(ov)
        cleaned["type"] = kind
        cleaned["start_word"] = start_word
        cleaned["duration_s"] = dur
        safe.append(cleaned)
    safe.sort(key=lambda item: item["start_word"])
    return safe


def _inject_cadence_labels(overlays: list, vo_duration: float) -> list[dict]:
    """
    Insert label cards into gaps that exceed MAX_VISUAL_GAP_S.

    The gap timeline is built from actual overlay start/end times only —
    NOT from synthetic time-grid events — so gaps are correctly identified
    before any filler is added.
    """
    # Collect the timeline boundaries from existing overlays
    bounds: set[float] = {0.0, vo_duration}
    for ov in overlays:
        s, e = _ov_start(ov), _ov_end(ov)
        if 0 < s < vo_duration:
            bounds.add(s)
        if 0 < e < vo_duration:
            bounds.add(e)
    timeline = sorted(bounds)

    cadence_labels = ["REAL EXAMPLE", "SIMPLE MATH", "THIS IS KEY", "TIME MATTERS"]
    injected = list(overlays)
    label_idx = 0
    for i in range(len(timeline) - 1):
        gap = timeline[i + 1] - timeline[i]
        if gap > MAX_VISUAL_GAP_S:
            midpoint = timeline[i] + gap / 2.0
            injected.append({
                "type": "label",
                "text": cadence_labels[label_idx % len(cadence_labels)],
                "start_word": int(midpoint * WPS),
                "duration_s": min(2.1, gap - 0.2),
            })
            label_idx += 1

    return injected


# ---------------------------------------------------------------------------
# Audio helpers
# ---------------------------------------------------------------------------

def _mean_volume_db(path: Path) -> float | None:
    result = subprocess.run(
        [_bin("ffmpeg"), "-hide_banner", "-i", str(path), "-af", "volumedetect", "-f", "null", "-"],
        capture_output=True, text=True, timeout=120,
    )
    text = (result.stderr or "") + "\n" + (result.stdout or "")
    m = re.search(r"mean_volume:\s*(-?\d+(?:\.\d+)?)\s*dB", text)
    return float(m.group(1)) if m else None


# ---------------------------------------------------------------------------
# Video probe / quality gate
# ---------------------------------------------------------------------------

def _probe_video(path: Path) -> dict:
    result = subprocess.run(
        [_bin("ffprobe"), "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", str(path)],
        capture_output=True, text=True, timeout=30, check=True,
    )
    return json.loads(result.stdout)


def _quality_gate(output_path: Path, expected_duration: float) -> None:
    probe = _probe_video(output_path)
    streams = probe.get("streams", [])
    video = next((s for s in streams if s.get("codec_type") == "video"), None)
    if not video:
        raise RuntimeError("Short output missing video stream")
    if int(video.get("width", 0)) != SHORT_W or int(video.get("height", 0)) != SHORT_H:
        raise RuntimeError(f"Wrong dimensions: {video.get('width')}x{video.get('height')}")
    if str(video.get("pix_fmt", "")) != "yuv420p":
        raise RuntimeError(f"Wrong pixel format: {video.get('pix_fmt')}")
    duration = float(probe.get("format", {}).get("duration", 0.0) or 0.0)
    if abs(duration - expected_duration) > 3.0:
        raise RuntimeError(f"Duration drift: rendered {duration:.1f}s vs voiceover {expected_duration:.1f}s")
    mean_db = _mean_volume_db(output_path)
    if mean_db is not None and mean_db < -19.5:
        raise RuntimeError(f"Audio too quiet: mean {mean_db:.1f} dB")


def _get_voiceover_duration(path: Path) -> float:
    result = subprocess.run(
        [_bin("ffprobe"), "-v", "quiet", "-print_format", "json", "-show_format", str(path)],
        capture_output=True, text=True, timeout=30, check=True,
    )
    return float(json.loads(result.stdout)["format"]["duration"])


# ---------------------------------------------------------------------------
# Main render entry point
# ---------------------------------------------------------------------------

def render(
    voiceover_path: Path,
    script_data: dict,
    output_path: Path = OUTPUT_SHORT,
    bgmusic_path: Path = BGMUSIC_PATH,
) -> Path:
    """
    Render a standalone YouTube Short.

    Strategy: Pillow pre-compositing (fast, CI-safe)
    ─────────────────────────────────────────────────
    1. Build gradient background image (Pillow).
    2. Sanitize script overlays; inject cadence labels into visual gaps.
    3. Compute segment boundaries from all overlay start/end times.
    4. For each segment, composite background + active overlays into a PNG (Pillow).
    5. FFmpeg concat demuxer encodes the PNG sequence — no overlay filter graph,
       no -loop 1 inputs, no timeout risk.
    6. Mix voiceover + background music with loudnorm.
    """
    if not voiceover_path.exists():
        raise FileNotFoundError(f"Voiceover not found: {voiceover_path}")

    work_dir = WORKSPACE / "short_work"
    work_dir.mkdir(parents=True, exist_ok=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    vo_duration = _get_voiceover_duration(voiceover_path)
    logger.info("Short voiceover duration: %.1fs", vo_duration)

    pillar = script_data.get("pillar", "investing")
    bg_img = _make_background_image(pillar)

    # Step 1: clean overlays from script
    overlays = _sanitize_overlays(script_data.get("overlays", []), vo_duration)

    # Step 2: inject cadence labels into actual visual gaps
    overlays = _inject_cadence_labels(overlays, vo_duration)
    overlays = _sanitize_overlays(overlays, vo_duration)  # re-sort + re-clamp after injection
    logger.info("Total overlays after cadence injection: %d", len(overlays))

    # Step 3: segment boundaries from overlay start/end times
    from PIL import Image
    events: set[float] = {0.0, vo_duration}
    for ov in overlays:
        s, e = _ov_start(ov), _ov_end(ov)
        if 0 < s < vo_duration:
            events.add(s)
        if 0 < e < vo_duration:
            events.add(e)
    events_sorted = sorted(events)

    # Step 4: composite each segment frame with Pillow
    seg_dir = work_dir / "segments"
    seg_dir.mkdir(exist_ok=True)
    concat_lines: list[str] = []

    for i in range(len(events_sorted) - 1):
        t_start = events_sorted[i]
        t_end   = events_sorted[i + 1]
        t_mid   = (t_start + t_end) / 2
        duration = t_end - t_start

        active = [ov for ov in overlays if _ov_start(ov) <= t_mid < _ov_end(ov)]

        frame = bg_img.copy()
        for ov in active:
            frame = Image.alpha_composite(frame, _make_overlay_image(ov))

        seg_path = seg_dir / f"seg_{i:03d}.png"
        frame.convert("RGB").save(seg_path)
        concat_lines.append(f"file '{seg_path.resolve()}'\nduration {duration:.4f}")

    # FFmpeg concat demuxer requires the last entry to be repeated without a duration line
    if concat_lines:
        last_seg = seg_dir / f"seg_{len(events_sorted) - 2:03d}.png"
        concat_lines.append(f"file '{last_seg.resolve()}'")

    concat_file = work_dir / "segments.txt"
    concat_file.write_text("\n".join(concat_lines))
    logger.info("Composited %d segment frames via Pillow", len(events_sorted) - 1)

    # Step 5: audio filter (loudnorm + optional bgmusic)
    if bgmusic_path.exists():
        audio_filter = (
            "[1:a]volume=1.0[voice];"
            "[2:a]volume=0.09[music];"
            "[voice][music]amix=inputs=2:duration=first[mix];"
            f"[mix]loudnorm=I={TARGET_LOUDNESS}:TP=-1.5:LRA=7[a]"
        )
        audio_inputs = ["-i", str(voiceover_path), "-i", str(bgmusic_path)]
    else:
        audio_filter = f"[1:a]loudnorm=I={TARGET_LOUDNESS}:TP=-1.5:LRA=7[a]"
        audio_inputs = ["-i", str(voiceover_path)]

    # Step 6: FFmpeg encode — concat image sequence + audio only
    # -vf is valid here: video comes from concat demuxer (not from filter_complex),
    # while filter_complex handles audio only.
    cmd = [
        _bin("ffmpeg"), "-y",
        "-f", "concat", "-safe", "0", "-i", str(concat_file),
        *audio_inputs,
        "-filter_complex", audio_filter,
        "-map", "0:v",
        "-map", "[a]",
        "-vf", f"scale={SHORT_W}:{SHORT_H}:force_original_aspect_ratio=disable,fps=30,setsar=1",
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "23",
        "-pix_fmt", "yuv420p",
        "-profile:v", "high",
        "-g", "60",
        "-c:a", "aac", "-b:a", "128k",
        "-movflags", "+faststart",
        str(output_path),
    ]

    logger.info("Encoding Short (%d segments, %d overlays)...", len(events_sorted) - 1, len(overlays))
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        raise RuntimeError(f"Short render failed:\n{result.stderr[-1000:]}")

    if not output_path.exists() or output_path.stat().st_size < 50_000:
        raise RuntimeError(f"Short output missing or too small: {output_path}")

    _quality_gate(output_path, vo_duration)

    logger.info("Short rendered: %s (%.1f MB)", output_path, output_path.stat().st_size / 1_048_576)
    return output_path
